### ISSUE TITLE
sed: 1: "db.json": extra characters at the end of d command on macos 10.10

### ISSUE THREAD

**Issue by oonid** [danielebailo/couchdb-dump#36]
I try to backup remote couchdb, i use macos 10.10
bash couchdb-backup.sh -b -H 1.2.3.4 -d _users -f db._users.json -u uuuu -p pppp

here's the output:
... INFO: File contains Windows carridge returns- converting...
... INFO: Completed successfully.
... INFO: Amending file to make it suitable for Import.
... INFO: Stage 1 - Document filtering
sed: 1: "db._users.json": extra characters at the end of d command

**Comment by chatzipan** [comment]
I replaced all sed -i instances with sed -i '' and it worked like a charm.

**Comment by dalgibbard** [comment]
Interesting! I've been struggling for time to test this and probably won't get around to it until next week (though I do at least have a Mac now); feel free to raise a pull request in the meantime :)

**Comment by KingScooty** [comment]
Yep, having the same issue on OSX El Capitan. Will use @chatzipan's pull request until it's merged.

**Comment by dalgibbard** [comment]
Merged; closing. Thanks!

**Comment by theo01** [comment]
Just came accross this issue, which lead to the following error in linux:

$ ./couchdb-backup.sh -b -H 172.17.0.3 -P 5984 -d mydb -f mydb_dump.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19543    0 19543    0     0  4997k      0 --:--:-- --:--:-- --:--:-- 6361k
... INFO: File contains Windows carridge returns- converting...
... INFO: Completed successfully.
... INFO: Amending file to make it suitable for Import.
... INFO: Stage 1 - Document filtering
sed: can't read s/.*,"doc"://g: No such file or directory
Stage failed.
This is because the linux sed implemenation differ from osx, it expect sed -i or sed -isomething but not sed -i something.

Here is a pull request #41 in order to fix this issue and pass the right sed -i according to the os type.
Also mentionned in #40.
