### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by konrad-2013** [danielebailo/couchdb-dump#42]
Hi,
really nice script, but could you please upload a license for it (e.g. Apache 2.0)?
I really like that script and would like to use it at work. But I can only use it, if there is a license attached which allows commercial usage... 

Thanks in advance
Konrad

**Comment by dalgibbard** [comment]
Fair point. I'd suggest either the BSD licensing or better yet, the WTFPL: http://www.wtfpl.net

The free'r the better! :)

**Comment by danielebailo** [comment]
I'm having a look at  http://choosealicense.com/
Licensing can be important in our case because private sector is involved.
Let's think a bit about it.

I'll be back as soon as my mind is more clear about what license to use (it
may take years in principle :), but I promise to do it within a week :))
best


Daniele

http://www.danielebailo.it/


2015-11-16 0:10 GMT+01:00 Darren Gibbard <notifications@github.com>:

**Comment by dalgibbard** [comment]
It's only bash code; no particular executable code is being shipped - so theoretically, as long as the license negates any liability (and is common enough for orgs to include in their various management processes) it should be sufficient right?

If we could avoid GPLv3 though, that would be my only personal requirement (it makes it difficult for me to contribute otherwise). FSF/OSI compliant licensing should cover the majority of supported licenses within organisations though (ie. the most common/realistic ones). see: https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses#Approvals for example.

Eager to see which one you go with :D

**Comment by konrad-2013** [comment]
Hi,
thanks for the fast response. For my company GPL would not be usable form a legal perspective, so I would agree with Darren, that avoiding GPL would be nice :-)

**Comment by danielebailo** [comment]
Hi,
I studied a bit, here are my remarks:
considering the software is relatively small, bash based (no particular
executable code is being shipped as Darren evidenced), and that my only
goal is to make it as open and free as possible with the condition that
Author(s) is (are) cited, I think we can go with the MIT license.

MIT license is also very short and simple
(http://choosealicense.com/licenses/mit/) , which is definitely a +1 for me.

Darren, your view?
Best

Daniele

http://www.danielebailo.it/ <http://danielebailo.wordpress.com/>


2015-11-17 0:09 GMT+01:00 Konrad <notifications@github.com>:

**Comment by dalgibbard** [comment]
LGTM

**Comment by danielebailo** [comment]
Great.
Darren, seen the huge contribution and effort, if you agree I'll include
you as Author.

best



2015-11-19 12:20 GMT+01:00 Darren Gibbard <notifications@github.com>:

> LGTM




Daniele

http://www.danielebailo.it/ <http://danielebailo.wordpress.com/>

**Comment by dalgibbard** [comment]
It would make me a very happy bunny :) :+1:

**Comment by danielebailo** [comment]
Just did it.
Darren please update with your full details.
ciao!

**Comment by dalgibbard** [comment]
Done :)

**Comment by konrad-2013** [comment]
Great, thanks guys! This helps me a lot :-)
