### ISSUE TITLE
Taking backup for all revisions

### ISSUE THREAD

**Issue by mkaliyannan** [danielebailo/couchdb-dump#70]
I am wondering is there any way to take a backup for all revisions ?

**Comment by dalgibbard** [comment]
For all historical revisions of all individual documents I assume you mean?

That requirement is out of scope for this project for sure, for a few reasons:
* There's not many times when old revision data is useful...
* It's easier to copy the entire DB file on disk if you want all historical data (and probably less IO intensive)
* In order to do this programmatically, you would need to get every document from the _all_docs endpoint, and then iterate through each document individually, calling ```/<db>/<doc_id>?revs=true```, and then iterate through every returned revision with ```/<db>/<doc_id>?rev=<rev>``` -- and then decide on a schema to store these on disk, and _then_ work out how to POST documents with a pre-determined ref back into a clean DB... I'm pretty sure that's not possible (unless you don't care about the revision specifically, but the data, then it's feasible, but still excessive effort 😃 )
